// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdiuktbipmqqvntigjlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkaXVrdGJpcG1xcXZudGlnamx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzQ5NTksImV4cCI6MjA2NDYxMDk1OX0.HqZ0BGzIWsnWHaorRk8l-nD5LjgM9NamVsqlwTFWCFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);